import {createHmac} from 'node:crypto';
import {initializeApp} from 'firebase-admin/app';
import {FieldValue,getFirestore} from 'firebase-admin/firestore';
import {onRequest} from 'firebase-functions/v2/https';
import {defineSecret} from 'firebase-functions/params';
initializeApp();const db=getFirestore();
const mpesaKey=defineSecret('MPESA_CONSUMER_KEY'),mpesaSecret=defineSecret('MPESA_CONSUMER_SECRET'),mpesaPasskey=defineSecret('MPESA_PASSKEY'),mpesaShortcode=defineSecret('MPESA_SHORTCODE'),mpesaCallbackUrl=defineSecret('MPESA_CALLBACK_URL'),paystackKey=defineSecret('PAYSTACK_SECRET_KEY');
const allowed=new Set(['https://www.tekntandao.com','https://tekntandao.com','http://localhost:5500','http://127.0.0.1:5500']);
function cors(req,res){const origin=req.headers.origin;if(origin&&allowed.has(origin))res.set('Access-Control-Allow-Origin',origin);res.set('Vary','Origin');res.set('Access-Control-Allow-Headers','Content-Type');res.set('Access-Control-Allow-Methods','POST,OPTIONS');if(req.method==='OPTIONS'){res.status(204).send('');return true}return false}
const fail=(res,status,msg)=>res.status(status).json({error:msg});
function normalizeItems(items){if(!Array.isArray(items)||!items.length||items.length>30)throw new Error('Invalid cart');return items.map(x=>({productId:String(x.productId||'').trim(),quantity:Number(x.quantity)})).map(x=>{if(!/^[a-z0-9_-]{2,80}$/i.test(x.productId)||!Number.isInteger(x.quantity)||x.quantity<1||x.quantity>20)throw new Error('Invalid cart item');return x})}
async function priceCart(items){const clean=normalizeItems(items);const rows=[];let totalKsh=0;for(const item of clean){const snap=await db.collection('products').doc(item.productId).get();if(!snap.exists)throw new Error(`Product ${item.productId} not found`);const p=snap.data();if(p.active!==true)throw new Error(`${p.name||item.productId} is unavailable`);const priceKsh=Number(p.priceKsh);if(!Number.isInteger(priceKsh)||priceKsh<1)throw new Error('Invalid product price');if(Number.isInteger(p.stock)&&p.stock<item.quantity)throw new Error(`Not enough stock for ${p.name}`);rows.push({productId:item.productId,name:String(p.name||item.productId),quantity:item.quantity,priceKsh,lineTotalKsh:priceKsh*item.quantity});totalKsh+=priceKsh*item.quantity}return{items:rows,totalKsh}}
async function createOrder(req,provider){const cart=await priceCart(req.body?.items);const ref=db.collection('orders').doc();await ref.set({orderId:ref.id,provider,status:'pending',customer:{name:String(req.body?.name||'').slice(0,120),email:String(req.body?.email||'').slice(0,200),phone:String(req.body?.phone||'').replace(/\D/g,'').slice(-15)},...cart,createdAt:FieldValue.serverTimestamp(),updatedAt:FieldValue.serverTimestamp()});return{ref,cart}}
async function mpesaToken(){const raw=Buffer.from(`${mpesaKey.value()}:${mpesaSecret.value()}`).toString('base64');const r=await fetch('https://api.safaricom.co.ke/oauth/v1/generate?grant_type=client_credentials',{headers:{Authorization:`Basic ${raw}`}});const j=await r.json();if(!r.ok||!j.access_token)throw new Error(j.errorMessage||'M-Pesa authentication failed');return j.access_token}
function mpesaTimestamp(){const d=new Date();const p=n=>String(n).padStart(2,'0');return `${d.getFullYear()}${p(d.getMonth()+1)}${p(d.getDate())}${p(d.getHours())}${p(d.getMinutes())}${p(d.getSeconds())}`}
export const createMpesaCheckout=onRequest({region:'europe-west1',secrets:[mpesaKey,mpesaSecret,mpesaPasskey,mpesaShortcode,mpesaCallbackUrl]},async(req,res)=>{try{if(cors(req,res))return;if(req.method!=='POST')return fail(res,405,'POST required');const phone=String(req.body?.phone||'').replace(/\D/g,'');if(!/^2547\d{8}$/.test(phone)&&!/^2541\d{8}$/.test(phone))return fail(res,400,'Use a Kenyan phone in 2547… or 2541… format');const {ref,cart}=await createOrder(req,'mpesa');const ts=mpesaTimestamp(),shortcode=mpesaShortcode.value();const password=Buffer.from(`${shortcode}${mpesaPasskey.value()}${ts}`).toString('base64');const token=await mpesaToken();const r=await fetch('https://api.safaricom.co.ke/mpesa/stkpush/v1/processrequest',{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({BusinessShortCode:shortcode,Password:password,Timestamp:ts,TransactionType:'CustomerPayBillOnline',Amount:cart.totalKsh,PartyA:phone,PartyB:shortcode,PhoneNumber:phone,CallBackURL:mpesaCallbackUrl.value(),AccountReference:`TT-${ref.id.slice(0,12)}`,TransactionDesc:'TeknTandao ICT order'})});const j=await r.json();if(!r.ok||!j.CheckoutRequestID){await ref.update({status:'payment_init_failed',paymentError:j,updatedAt:FieldValue.serverTimestamp()});return fail(res,502,j.errorMessage||j.ResponseDescription||'M-Pesa request failed')}await ref.update({mpesa:{checkoutRequestId:j.CheckoutRequestID,merchantRequestId:j.MerchantRequestID},updatedAt:FieldValue.serverTimestamp()});res.json({orderId:ref.id,message:'M-Pesa prompt sent. Complete payment on your phone.'})}catch(e){fail(res,400,String(e.message||e))}});
export const mpesaCallback=onRequest({region:'europe-west1'},async(req,res)=>{try{const cb=req.body?.Body?.stkCallback;if(!cb?.CheckoutRequestID)return res.json({ResultCode:0,ResultDesc:'Accepted'});const q=await db.collection('orders').where('mpesa.checkoutRequestId','==',cb.CheckoutRequestID).limit(1).get();if(!q.empty){const meta=Object.fromEntries((cb.CallbackMetadata?.Item||[]).map(x=>[x.Name,x.Value]));await q.docs[0].ref.update({status:cb.ResultCode===0?'paid':'payment_failed',mpesaResult:{resultCode:cb.ResultCode,resultDesc:cb.ResultDesc,receipt:meta.MpesaReceiptNumber||null,amount:meta.Amount||null,phone:meta.PhoneNumber||null},updatedAt:FieldValue.serverTimestamp()})}res.json({ResultCode:0,ResultDesc:'Accepted'})}catch(e){res.status(500).json({error:String(e.message||e)})}});
export const createPaystackCheckout=onRequest({region:'europe-west1',secrets:[paystackKey]},async(req,res)=>{try{if(cors(req,res))return;if(req.method!=='POST')return fail(res,405,'POST required');const email=String(req.body?.email||'').trim();if(!/^\S+@\S+\.\S+$/.test(email))return fail(res,400,'Valid email required for Paystack');const {ref,cart}=await createOrder(req,'paystack');const callback=String(req.body?.origin||'https://www.tekntandao.com').replace(/\/$/,'')+'/shop.html?payment=paystack';const r=await fetch('https://api.paystack.co/transaction/initialize',{method:'POST',headers:{Authorization:`Bearer ${paystackKey.value()}`,'Content-Type':'application/json'},body:JSON.stringify({email,amount:cart.totalKsh*100,currency:'KES',reference:ref.id,callback_url:callback,metadata:{orderId:ref.id}})});const j=await r.json();if(!r.ok||j.status!==true){await ref.update({status:'payment_init_failed',paymentError:j,updatedAt:FieldValue.serverTimestamp()});return fail(res,502,j.message||'Paystack initialization failed')}await ref.update({paystack:{reference:ref.id,accessCode:j.data.access_code},updatedAt:FieldValue.serverTimestamp()});res.json({orderId:ref.id,authorizationUrl:j.data.authorization_url})}catch(e){fail(res,400,String(e.message||e))}});
export const paystackWebhook=onRequest({region:'europe-west1',secrets:[paystackKey]},async(req,res)=>{try{const signature=req.headers['x-paystack-signature'];const expected=createHmac('sha512',paystackKey.value()).update(req.rawBody).digest('hex');if(signature!==expected)return res.status(401).send('Invalid signature');const event=req.body;if(event.event==='charge.success'){const reference=String(event.data?.reference||'');const ref=db.collection('orders').doc(reference);const snap=await ref.get();if(snap.exists){const order=snap.data();const paidKsh=Math.round(Number(event.data.amount||0)/100);if(paidKsh===order.totalKsh)await ref.update({status:'paid',paystackResult:{reference,channel:event.data.channel||null,paidAt:event.data.paid_at||null},updatedAt:FieldValue.serverTimestamp()})}}res.status(200).send('ok')}catch(e){res.status(500).send('error')}});
